### ISSUE TITLE
Settings unavailable

### ISSUE THREAD

**Issue by MaxDev98** [bugness-chl/sendrecurringinvoicebymail#1]
Using Dolibarr 13.0.0, i am unable to find any settings für this module. 
I edited the template text inside the database in order to use module for my use case. 

Is there any option to set a specific template to one recurring invoice?
e.g. rec_invoice_template_customer1: E-Mail Template invoice_sepa
rec_invoice_template_customer2: E-Mail template invoice_normal

Thanks!

**Comment by bugness-chl** [comment]
Sorry, this was a quick-and-dirty module, the internationalization has not been finalized.

It seems the template won't appear at the URL `/admin/mails_templates.php` (Home > setup > emails > Emails templates) if the Dolibarr instance is not in french or the `Enable multilanguage support for customer or vendor relationships` option in Home > setup > display is left unchecked. I hope to correct and enhance it soon.

As for your request to have a specific template for an invoice, managing the data in the module will need new forms and database tables, and could be quite some work. As a hack, maybe you can modify this module so that it reuses the private comment field of the invoice as a mail template. Probably with a little security check (for example, only using text between `---email-template-start---` and `---email-template-end---`) so that it doesn't send whatever private info to the customer :-)
Again, this module is not really advanced, but it's quite simple so don't fear to adapt it to your needs. Keep me informed if you do it, it may be interesting to add it in the base code.

**Comment by bugness-chl** [comment]
Hello,

1. Mail template should appear for every language in new installations (in case of old installation, execute `update llx_c_email_templates set lang = '' where module = 'sendrecurringinvoicebymail';` or reset the whole thing by deactivating/reactivating the module ) (commit 36a17c4590)
2. the idea of customizing the message for each invoice template seemed interesting to me so 3f1416499453 brings a beta of this feature. As said, adding screens and databases tables is a little too much work for me now, so the hack is to use the `note_private` field of the template, using delimiters for the time being. For example :
```
%%% sendrecurringinvoicebymail::body
Hello dear client,
Please find attached invoice __REF__...
%%%
Other private notes.
```

See the Readme for a more thorough example. If you can test it, I would be delighted.

**Comment by bugness-chl** [comment]
Hello @MaxDev98 ,

Little ping to mention that, regarding 2°, I actually made the forms and databases needed to properly deal with customization. [Small screenshot here](https://raw.githubusercontent.com/bugness-chl/sendrecurringinvoicebymail/0.3.1/img/screenshot1.png).

The hack mentioned before is deprecated : any data it holds will be imported into the new system with the 0.3.1 upgrade, and it will no longer work afterwards.

Feedback welcome !
