### ISSUE TITLE
No scheduled job

### ISSUE THREAD

**Issue by dploeger** [bugness-chl/sendrecurringinvoicebymail#5]
I've installed the module using the release here on Github, but in the scheduled jobs module, there's no job to run the class. Is that how it is supposed to be, is it a bug or am I missing something?

**Comment by bugness-chl** [comment]
This is how it's supposed to be : this module hooks himself at the end of the "recurring invoice" scheduled job.

The suggestion for scheduled job in the readme.md is because this module will be mostly useless if the scheduled jobs module is disabled : no mail is sent when you manually generate an invoice from a recurring one, this module is triggered only when the generation occurs via cron/scheduled jobs.

Feel free to reword if you feel the need and I'll include it in the readme.md.

**Comment by dploeger** [comment]
Allright, I just wanted to make sure. Thanks!
