### ISSUE TITLE
[CSRF] Issue saving settings

### ISSUE THREAD

**Issue by dpnullvoid** [bugness-chl/sendrecurringinvoicebymail#8]
Hello! 
I was able to install the module but I have an error saving settings on 'Sending by email'.
How can I fix this? My server is not behind a proxy :( 

Token not provided refers for the user token to put in the cron command?

`Access to this page this way (POST method or GET with a sensible value for 'action' parameter) is refused by CSRF protection in main.inc.php. Token not provided. If you access your server behind a proxy using url rewriting and the parameter is provided by caller, you might check that all HTTP header are propagated (or add the line $dolibarr_nocsrfcheck=1 into your conf.php file or MAIN_SECURITY_CSRF_WITH_TOKEN to 0 instead of 2 into setup). `

Thanks!

**Comment by dpnullvoid** [comment]
i got my answer :)

https://www.dolibarr.org/forum/t/access-by-post-method-refused-by-csrf-protection-in-main-inc-php/18466

**Comment by bugness-chl** [comment]
Hello!

There is definitely an issue, I didn't spot it because `MAIN_SECURITY_CSRF_WITH_TOKEN` default to 1 or 2 in new installation (starting with Dolibarr [15](https://github.com/Dolibarr/dolibarr/blob/24703a0f3d63dc2f6f900cbc0147abed4f6335d2/ChangeLog#L1569C3-L1569C3) or [16](https://github.com/Dolibarr/dolibarr/blob/24703a0f3d63dc2f6f900cbc0147abed4f6335d2/ChangeLog#L1114)) but mine was an upgrade so the value was kept at 0. The fix seems simple but I'll test some more before releasing.

Reopening the issue as a reminder. Thanks for the report !

**Comment by bugness-chl** [comment]
Fixed by d3bac76b2ee415fd4da59d1e869b46fd9b48f0f6 and [release 0.3.3](https://github.com/bugness-chl/sendrecurringinvoicebymail/releases/tag/0.3.3).

Please install it and remember to revert your modifications to avoid lowering your dolibarr instance's security.
